name: pypsa-pl
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pypsa
  - snakemake=7.32.4  # this version works better on ARM
  - pandas
  - geopandas
  - matplotlib
  - numpy
  - xarray
  - netcdf4
  - cartopy
  - scipy
  - jupyter
  - ruamel.yaml
  - pip
  - pip:
      - pypsa-eur  # optional if you want to inherit from PyPSA-Eur
